### ISSUE TITLE
How to call 808s and heartbreak?

### ISSUE THREAD

**Issue by arlen-yu** [tomcek112/KanyeRest#2]
http://www.kanyerest.xyz/api/album/808s_&_heartbreak doesn't seem to work, played around and couldn't find anything that gave a response.

**Comment by tomcek112** [comment]
Hi Arlen, I didn't actually knew people where using this. What are you doing with it?

We generally use HTML escaping for all requests so the correct query for 808s & heartbreak would be: http://www.kanyerest.xyz/api/album/808s_&amp;_heartbreak

Looking forward to more questions or suggestions from you!

**Comment by arlen-yu** [comment]
Hey! Right now I'm working on an in depth text analysis and data visualization of Kanye's albums. Your API saved me a lot of scraping. Just started the project, so I'll update you with any questions/suggestions if they come.
